### ISSUE TITLE
GOPRO_flow数据集

### ISSUE THREAD

**Issue by oyryrookie** [plusgood-steven/ID-Blau#1]
能不能转存一下GOPRO_flow数据集到百度网盘，太大了

**Comment by plusgood-steven** [comment]
你好，
感謝你對我們的work感到興趣，
由於GOPRO_flow資料集約為32G且本身沒有百度帳號，
因此可能還是需要依照README上提供的步驟自行生成，
之後有可能會放在Google Drive上，
但目前來說暫時沒有提供，謝謝 !

**Comment by plusgood-steven** [comment]
您好，
已可在README找尋到GOPRO_flow資料集的下載連結，
目前是使用onedrive的方式提供。
