### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by luciferincc** [plusgood-steven/ID-Blau#2]
Hi, thanks for your work.

When I wanted to test on the GoPro dataset, the Google Drive link you provided does not have the corresponding weights. Could you please provide the weights for the deblurring model mentioned in the paper?

**Comment by plusgood-steven** [comment]
Thank you for your interest in our work. 
I will release the weights soon, but I've been quite busy recently. 
Please stay tuned.

**Comment by plusgood-steven** [comment]
Hi, 
We have provided the weights for the deblurring model mentioned in the paper. 
You can find them in the Google Drive link now.
